theme: jekyll-theme-cayman
#theme: marella/jekyll-theme-documentation


title: Albert Patera 
description: WWW developer, android apps & programmer

github:
  is_project_page: false
  zip_url: 

owner:
  name: Albert Patera
  avatar: bio-photo.jpg
  bio: "Everything is posible...."
  email: albert.patera@gmail.com

configur:
  css: 
    path: /assets/css/style.css?v=